version: '3.9'

services:

  web:
    container_name: dental-app
    hostname: dental-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py createsuperuser --noinput || true &&
               python manage.py runserver 0.0.0.0:8000 --noreload"
    restart: always
    environment:
      ENV: ${ENV}
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    volumes:
      - ${DATA_PERSISTENCE_FOLDER}:/app/data
    ports:
      - "8000:8000"
    networks:
      - dental-network

networks:
  dental-network:
    external: true